#!/usr/bin/env bash
# Configures nginx to listen on port 80 if config file is not linked correctly
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
