#!/usr/bin/env bash
# a Bash script that displays numbers from 1 to 100.
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number
# In a list format

for (( i=1; i<=100; i++ ))
do
    div3=$(( i % 3 ))
    div5=$(( i % 5 ))
    if [ "$div3" -eq 0 ] && [ "$div5" -eq 0 ]; then
        echo "FizzBuzz"
    elif [ "$div3" -eq 0 ]; then
        echo "Fizz"
    elif [ "$div5" -eq 0 ]; then
        echo "Buzz"
    else
        echo "$i"
    fi
done
