#!/usr/bin/env bash
# A Bash Script that uses a while loop with an if, elif, else statement
# That loops from 1 to 10
# displays 'bad luck' on the 4th iteration
# displays 'good luck' on the 8th iteration
# displays 'Best School' for every other iteration

i=1
while [ "$i" -le 10 ]
do
    if [ "$i" -eq 4 ]; then
        echo "bad luck"
    elif [ "$i" -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    i=$((i + 1))
done
