#!/usr/bin/env bash
# runs NGINX as a user {nginx} on port 8080
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
# kill any processes that might prevent nginx running on port 8080
pkill apache2
sudo -u nginx service nginx start
